return function(p, options)
  local core = {
    Normal               = { fg = p.fg, bg = p.bg },
    NormalNC             = { link = 'Normal' },
    NormalFloat          = { fg = p.fg, bg = p.bg },
    FloatBorder          = { fg = p.muted, bg = p.bg },
    FloatTitle           = { fg = p.orange, bold = true },
    FloatFooter          = { link = 'FloatTitle' },
    FloatShadow          = { bg = p.black, blend = 80 },
    FloatShadowThrough   = { bg = p.black, blend = 100 },
    WinSeparator         = { fg = '#2e2e2e', bg = 'NONE' },
    VertSplit            = { link = 'WinSeparator' },
    WinBar               = { link = 'StatusLine' },
    WinBarNC             = { link = 'StatusLineNC' },

    Cursor               = { fg = p.black, bg = p.white },
    lCursor              = { link = 'Cursor' },
    CursorIM             = { link = 'Cursor' },
    TermCursor           = { link = 'Cursor' },
    iCursor              = { link = 'Cursor' },
    CursorLine           = { bg = p.cursor_line },
    CursorColumn         = { bg = p.cursor_line },
    ColorColumn          = { bg = p.color_column },
    VirtColumn           = { fg = '#404040', bg = 'NONE' },
    CursorLineNr         = { fg = p.orange },
    CursorLineFold       = { link = 'FoldColumn' },
    CursorLineSign       = { link = 'SignColumn' },
    LineNr               = { fg = p.line_nr, bg = p.line_nr_bg },
    LineNrAbove          = { link = 'LineNr' },
    LineNrBelow          = { link = 'LineNr' },
    FoldColumn           = { fg = p.muted, bg = '#181818' },
    Folded               = { fg = p.muted, bg = p.black },
    SignColumn           = { fg = p.green, bg = 'NONE' },
    MatchParen           = { fg = p.black, bg = p.orange, bold = true },

    Pmenu                = { fg = p.cyan, bg = p.black },
    PmenuSel             = { fg = p.fg, bg = p.gray },
    PmenuKind            = { fg = p.purple },
    PmenuKindSel         = { link = 'PmenuSel' },
    PmenuExtra           = { fg = p.comment },
    PmenuExtraSel        = { link = 'PmenuSel' },
    PmenuMatch           = { fg = p.orange, bold = true },
    PmenuMatchSel        = { fg = p.orange, bold = true },
    PmenuBorder          = { link = 'FloatBorder' },
    PmenuShadow          = { link = 'FloatShadow' },
    PmenuShadowThrough   = { link = 'FloatShadowThrough' },
    PmenuSbar            = { bg = p.darker },
    PmenuThumb           = { bg = p.cyan },
    ComplMatchIns        = { link = 'PmenuMatch' },
    PreInsert            = { link = 'PmenuMatch' },
    ComplHint            = { link = 'PmenuExtra' },
    ComplHintMore        = { link = 'PmenuExtra' },

    StatusLine           = { bg = 'NONE' },
    StatusLineNC         = { bg = 'NONE' },
    StatusLineTerm       = { link = 'StatusLine' },
    StatusLineTermNC     = { link = 'StatusLineNC' },
    TabLine              = { fg = p.gray, bg = p.dark },
    TabLineSel           = { fg = p.fg, bg = p.cursor_line, bold = true },
    TabLineFill          = { fg = p.dark, bg = p.dark },
    WildMenu             = { fg = p.cyan, bg = p.black },

    Search               = { fg = p.black, bg = '#ffe792' },
    CurSearch            = { fg = '#005f00', bg = '#afdf00', bold = true },
    IncSearch            = { link = 'CurSearch' },
    Substitute           = { link = 'CurSearch' },
    Visual               = { bg = '#005f87' },
    VisualNOS            = { bg = '#005f87' },
    QuickFixLine         = { link = 'CursorLine' },
    SnippetTabstop       = { link = 'Visual' },
    SnippetTabstopActive = { link = 'MatchParen' },

    DiffAdd              = { fg = '#f0cdc9', bg = '#567c44' },
    DiffChange           = { fg = '#fefefe', bg = '#404ea4' },
    DiffDelete           = { fg = '#c3c3c3', bg = '#a22e26', bold = true },
    DiffText             = { bg = '#4c4745', italic = true, bold = true },
    DiffTextAdd          = { link = 'DiffText' },
    Added                = { fg = '#afdf00', bg = p.panel },
    Changed              = { fg = '#4581ff', bg = p.panel },
    Removed              = { fg = '#ff4545', bg = p.panel },

    SpellBad             = { sp = '#ff0000', undercurl = true },
    SpellCap             = { sp = '#7070f0', undercurl = true },
    SpellLocal           = { sp = '#70f0f0', undercurl = true },
    SpellRare            = { sp = '#ffffff', undercurl = true },

    ErrorMsg             = { fg = p.red, bg = p.panel, bold = true },
    WarningMsg           = { fg = '#ffffff', bg = '#333333', bold = true },
    OkMsg                = { fg = p.green },
    StderrMsg            = { link = 'ErrorMsg' },
    StdoutMsg            = { link = 'ModeMsg' },
    ModeMsg              = { fg = p.yellow },
    MoreMsg              = { fg = p.yellow },
    Question             = { fg = p.cyan },
    MsgArea              = { link = 'Normal' },
    MsgSeparator         = { link = 'WinSeparator' },

    Directory            = { fg = p.green, bold = true },
    SpecialKey           = { fg = p.nontext },
    NonText              = { fg = p.nontext },
    EndOfBuffer          = { link = 'NonText' },
    Conceal              = { link = 'NonText' },
    Whitespace           = { link = 'NonText' },
    Menu                 = { link = 'Normal' },
    Scrollbar            = { link = 'PmenuSbar' },
    Tooltip              = { link = 'NormalFloat' },
    Title                = { fg = '#ef5939' },

    Comment              = { fg = p.comment, italic = options.italic_comments or false },
    Constant             = { fg = p.purple, bold = true },
    String               = { fg = p.yellow },
    Character            = { fg = p.yellow },
    Number               = { fg = p.purple },
    Boolean              = { fg = p.purple },
    Float                = { fg = p.purple },

    Identifier           = { fg = p.orange },
    Function             = { fg = p.green },

    Statement            = { fg = p.red, bold = true, italic = options.italic_keywords or false },
    Conditional          = { fg = p.red, bold = true, italic = options.italic_keywords or false },
    Repeat               = { fg = p.red, bold = true, italic = options.italic_keywords or false },
    Label                = { fg = p.yellow },
    Operator             = { fg = p.red },
    Keyword              = { fg = p.red, bold = true, italic = options.italic_keywords or false },
    Exception            = { fg = p.green, bold = true, italic = options.italic_keywords or false },

    PreProc              = { fg = p.green },
    Include              = { link = 'PreProc' },
    Define               = { fg = p.cyan },
    Macro                = { fg = '#c4be89' },
    PreCondit            = { fg = p.green, bold = true },

    Type                 = { fg = p.cyan },
    StorageClass         = { fg = p.orange },
    Structure            = { fg = p.cyan },
    Typedef              = { fg = p.cyan },

    Special              = { fg = p.cyan, bold = true },
    SpecialChar          = { fg = p.red, bold = true },
    Tag                  = { fg = p.green },
    Delimiter            = { fg = '#8f8f8f' },
    SpecialComment       = { fg = p.comment, bold = true, italic = options.italic_comments or false },
    Debug                = { fg = '#bca3a3', bold = true },

    Underlined           = { underline = true },
    Ignore               = { fg = p.gray, bg = p.bg },
    Error                = { fg = p.yellow, bg = '#1e0010' },
    Todo                 = { fg = '#ffffff', bg = p.bg, bold = true },
  }

  local treesitter = {
    ['@comment']                               = { link = 'Comment' },
    ['@string']                                = { link = 'String' },
    ['@string.escape']                         = { link = 'SpecialChar' },
    ['@string.regexp']                         = { link = 'String' },
    ['@string.special']                        = { link = 'SpecialChar' },
    ['@string.special.symbol']                 = { link = 'SpecialChar' },
    ['@string.special.path']                   = { link = 'String' },
    ['@string.special.url']                    = { link = 'Underlined' },
    ['@character']                             = { link = 'Character' },
    ['@character.special']                     = { link = 'SpecialChar' },
    ['@number']                                = { link = 'Number' },
    ['@number.float']                          = { link = 'Float' },
    ['@boolean']                               = { link = 'Boolean' },
    ['@constant']                              = { link = 'Constant' },
    ['@constant.builtin']                      = { link = 'Constant' },
    ['@constant.macro']                        = { link = 'Macro' },
    ['@variable']                              = { link = 'Identifier' },
    ['@variable.builtin']                      = { link = 'Identifier' },
    ['@property']                              = { link = 'Identifier' },
    ['@module']                                = { link = 'Structure' },
    ['@module.builtin']                        = { link = '@module' },
    ['@label']                                 = { link = 'Label' },
    ['@variable.parameter']                    = { link = 'Identifier' },
    ['@variable.parameter.builtin']            = { link = '@variable.parameter' },
    ['@variable.member']                       = { link = 'Identifier' },
    ['@parameter']                             = { link = '@variable.parameter' },
    ['@function']                              = { link = 'Function' },
    ['@function.builtin']                      = { link = 'Function' },
    ['@function.call']                         = { link = 'Function' },
    ['@function.macro']                        = { link = 'Macro' },
    ['@function.method']                       = { fg = '#47bbff' },
    ['@function.method.private']               = { fg = '#41ABE9', bold = false, italic = true },
    ['@function.method.call']                  = { link = '@function.method' },
    ['@constructor']                           = { link = 'Function' },
    ['@type']                                  = { link = 'Type' },
    ['@type.private']                          = { fg = '#5EC9DE', bold = false, italic = true },
    ['@type.builtin']                          = { link = 'Type' },
    ['@type.definition']                       = { link = 'Typedef' },
    ['@keyword']                               = { link = 'Keyword' },
    ['@keyword.coroutine']                     = { link = 'Keyword' },
    ['@keyword.function']                      = { link = 'Keyword' },
    ['@keyword.operator']                      = { fg = p.red, italic = options.italic_keywords or false },
    ['@keyword.import']                        = { link = 'Keyword' },
    ['@keyword.type']                          = { link = 'Keyword' },
    ['@keyword.modifier']                      = { link = 'Keyword' },
    ['@keyword.repeat']                        = { link = 'Repeat' },
    ['@keyword.return']                        = { link = 'Keyword' },
    ['@keyword.debug']                         = { link = 'Keyword' },
    ['@keyword.exception']                     = { link = 'Exception' },
    ['@keyword.conditional']                   = { link = 'Conditional' },
    ['@keyword.conditional.ternary']           = { link = '@keyword.conditional' },
    ['@keyword.directive']                     = { fg = p.green, italic = options.italic_keywords or false },
    ['@keyword.directive.define']              = { link = '@keyword.directive' },
    ['@operator']                              = { link = 'Operator' },
    ['@punctuation.delimiter']                 = { link = 'Delimiter' },
    ['@punctuation.bracket']                   = { link = 'Delimiter' },
    ['@punctuation.special']                   = { link = 'SpecialChar' },
    ['@attribute']                             = { link = '@boolean' },
    ['@attribute.builtin']                     = { link = '@attribute' },
    ['@comment.documentation']                 = { link = 'Comment' },
    ['@comment.error']                         = { fg = p.red, italic = options.italic_comments or false },
    ['@comment.warning']                       = { fg = p.yellow, italic = options.italic_comments or false },
    ['@comment.todo']                          = { fg = p.white, bg = p.bg, bold = true, italic = options.italic_comments or false },
    ['@comment.note']                          = { link = 'Comment' },
    ['@tag']                                   = { link = 'Tag' },
    ['@tag.builtin']                           = { link = '@tag' },
    ['@tag.attribute']                         = { link = '@attribute' },
    ['@tag.delimiter']                         = { link = 'Delimiter' },
    ['@tag.special']                           = { link = 'Special' },
    ['@tag.attribute.special']                 = { link = 'Keyword' },
    ['@markup.heading']                        = { link = 'Title' },
    ['@markup.strong']                         = { bold = true },
    ['@markup.italic']                         = { italic = true },
    ['@markup.strikethrough']                  = { strikethrough = true },
    ['@markup.underline']                      = { underline = true },
    ['@markup.heading.1']                      = { link = '@markup.heading' },
    ['@markup.heading.2']                      = { link = '@markup.heading' },
    ['@markup.heading.3']                      = { link = '@markup.heading' },
    ['@markup.heading.4']                      = { link = '@markup.heading' },
    ['@markup.heading.5']                      = { link = '@markup.heading' },
    ['@markup.heading.6']                      = { link = '@markup.heading' },
    ['@markup.quote']                          = { link = 'Comment' },
    ['@markup.math']                           = { link = 'Special' },
    ['@markup.link']                           = { link = 'Underlined' },
    ['@markup.link.label']                     = { link = 'Underlined' },
    ['@markup.link.url']                       = { link = 'Underlined' },
    ['@markup.raw']                            = { fg = '#489dad' },
    ['@markup.raw.block']                      = { link = '@markup.raw' },
    ['@markup.list']                           = { link = 'Special' },
    ['@markup.list.checked']                   = { link = 'Added' },
    ['@markup.list.unchecked']                 = { link = 'Todo' },
    ['@diff.plus']                             = { link = 'Added' },
    ['@diff.minus']                            = { link = 'Removed' },
    ['@diff.delta']                            = { link = 'Changed' },
    ['@markup.raw.markdown_inline']            = { fg = '#489dad' },
    ['@markup.link.label.markdown_inline']     = { fg = '#2758fe' },
    ['@string.document']                       = { link = 'Comment' },
    ['@string.documentation']                  = { link = '@string.document' },
    ['@string.html']                           = { link = 'String' },
    ['@string.heex']                           = { link = '@string.html' },
    ['@tag.html']                              = { link = '@tag' },
    ['@tag.heex']                              = { link = '@tag' },
    ['@tag.attribute.heex']                    = { link = '@attribute' },
    ['@macro.edoc']                            = { link = 'Comment' },
    ['@variable.prom']                         = { link = 'Identifier' },
    ['@constructor.prom']                      = { link = 'Function' },
    ['@type.prom']                             = { link = 'Debug' },
    ['@label.prom']                            = { link = 'Type' },
    ['@variable.openmetrics']                  = { link = '@variable.prom' },
    ['@constructor.openmetrics']               = { link = '@constructor.prom' },
    ['@type.openmetrics']                      = { link = '@type.prom' },
    ['@label.openmetrics']                     = { link = '@label.prom' },
    ['@type.comment.prom']                     = { link = 'NonText' },
    ['@type.comment.openmetrics']              = { link = 'NonText' },
    ['@string.special.path.dockerfile']        = { link = '@diff.delta' },
    ['@string.special.path.src.dockerfile']    = { link = '@diff.delta' },
    ['@string.special.path.dst.dockerfile']    = { link = '@diff.plus' },
    ['@string.special.image.name.dockerfile']  = { link = '@constant' },
    ['@string.special.image.tag.dockerfile']   = { link = '@label' },
    ['@string.special.image.alias.dockerfile'] = { link = '@constant' },
    ['@property.table_name.toml']              = { link = 'Constant' },
    ['@unit.css']                              = { link = 'SpecialChar' },
    ['@variable.declaration.css']              = { fg = '#bf66ff' },
    ['@variable.reference.css']                = { fg = '#bb7799', bold = true },
    ['@identifier.builtin.vue']                = { link = 'Keyword' },
    ['@tag.attribute.builtin']                 = { link = 'Keyword' },
    ['@tag.attribute.special']                 = { link = 'Special' },
    ['@identifier.unused']                     = { link = 'Comment' },
    ['@function.deprecated.erlang']            = { link = 'DiagnosticDeprecated' },
    jsxAttrib                                  = { link = '@attribute' },
  }

  local lsp = {
    LspReferenceWrite                                = { bg = '#5c7b36' },
    LspReferenceRead                                 = { bg = '#3c5bb1' },
    LspReferenceText                                 = { bg = '#3333ff' },
    LspReferenceTarget                               = { link = 'LspReferenceText' },
    LspInlayHint                                     = { fg = p.comment, bg = p.cursor_line },
    LspCodeLens                                      = { fg = p.comment },
    LspCodeLensSeparator                             = { link = 'LspCodeLens' },
    LspSignatureActiveParameter                      = { fg = p.orange, bold = true },

    DiagnosticError                                  = { fg = p.red },
    DiagnosticWarn                                   = { fg = p.yellow },
    DiagnosticInfo                                   = { fg = p.cyan },
    DiagnosticHint                                   = { fg = '#8cf8f7' },
    DiagnosticOk                                     = { fg = p.green },
    DiagnosticDeprecated                             = { strikethrough = true },
    DiagnosticUnnecessary                            = { fg = p.comment },
    DiagnosticUnderlineError                         = { sp = p.red, undercurl = true },
    DiagnosticUnderlineWarn                          = { sp = p.yellow, undercurl = true },
    DiagnosticUnderlineInfo                          = { sp = p.cyan, undercurl = true },
    DiagnosticUnderlineHint                          = { sp = '#8cf8f7', undercurl = true },
    DiagnosticUnderlineOk                            = { sp = p.green, undercurl = true },

    ['@lsp.mod.deprecated']                          = { strikethrough = true },
    ['@lsp.type.class']                              = { link = '@type' },
    ['@lsp.type.comment']                            = { link = '@comment' },
    ['@lsp.type.decorator']                          = { link = '@attribute' },
    ['@lsp.type.enum']                               = { link = '@type' },
    ['@lsp.type.enumMember']                         = { link = '@constant' },
    ['@lsp.type.event']                              = { link = '@type' },
    ['@lsp.type.function']                           = { link = '@function' },
    ['@lsp.type.interface']                          = { link = '@type' },
    ['@lsp.type.keyword']                            = { link = '@keyword' },
    ['@lsp.type.macro']                              = { link = 'Macro' },
    ['@lsp.type.method']                             = { link = '@function.method' },
    ['@lsp.type.modifier']                           = { link = '@keyword.modifier' },
    ['@lsp.type.namespace']                          = { link = '@module' },
    ['@lsp.type.number']                             = { link = '@number' },
    ['@lsp.type.operator']                           = { link = '@operator' },
    ['@lsp.type.parameter']                          = { link = '@variable.parameter' },
    ['@lsp.type.property']                           = { link = '@property' },
    ['@lsp.type.regexp']                             = { link = '@string.regexp' },
    ['@lsp.type.string']                             = { link = '@string' },
    ['@lsp.type.struct']                             = { link = '@type' },
    ['@lsp.type.type']                               = { link = '@type' },
    ['@lsp.type.typeParameter']                      = { link = '@type' },
    ['@lsp.type.variable']                           = { link = '@variable' },
    ['@lsp.typemod.string.injected.rust']            = { fg = '#a16600' },
    ['@lsp.typemod.function.documentation.rust']     = { fg = '#91b444' },
    ['@lsp.typemod.string.documentation']            = { link = '@string.document' },
    ['@lsp.typemod.property.declaration.typescript'] = { link = '@attribute' },
    ['@lsp.typemod.property.declaration']            = { link = '@attribute' },
    ['@lsp.type.property.swift']                     = { link = '@variable.member.swift' },
    ['@variable.member.swift']                       = { fg = '#3377ff' },
    ['@lsp.type.component.vue']                      = { link = 'Type' },
    ['@variable.builtin.self.swift']                 = { fg = '#ff6677', bold = true },
  }

  for _, severity in ipairs({ 'Error', 'Warn', 'Info', 'Hint', 'Ok' }) do
    for _, prefix in ipairs({
      'DiagnosticVirtualText',
      'DiagnosticVirtualLines',
      'DiagnosticFloating',
      'DiagnosticSign',
    }) do
      lsp[prefix .. severity] = { link = 'Diagnostic' .. severity }
    end
  end

  -- Neutral semantic modifiers leave the underlying Tree-sitter/type colors intact.
  for _, modifier in ipairs({
    'abstract',
    'async',
    'declaration',
    'defaultLibrary',
    'definition',
    'documentation',
    'modification',
    'readonly',
    'static',
  }) do
    lsp['@lsp.mod.' .. modifier] = {}
  end

  return { core, treesitter, lsp }
end
